// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8)
            {
                { typeof(global::SBPacketLib.ErrorCode), 0 },
                { typeof(global::SBPacketLib.ResultCode), 1 },
                { typeof(global::SBPacketLib.CSAuth), 2 },
                { typeof(global::SBPacketLib.CSChatMessage), 3 },
                { typeof(global::SBPacketLib.CSPing), 4 },
                { typeof(global::SBPacketLib.SCAuth), 5 },
                { typeof(global::SBPacketLib.SCChatMessage), 6 },
                { typeof(global::SBPacketLib.SCPong), 7 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new MessagePack.Formatters.SBPacketLib.ErrorCodeFormatter();
                case 1: return new MessagePack.Formatters.SBPacketLib.ResultCodeFormatter();
                case 2: return new MessagePack.Formatters.SBPacketLib.CSAuthFormatter();
                case 3: return new MessagePack.Formatters.SBPacketLib.CSChatMessageFormatter();
                case 4: return new MessagePack.Formatters.SBPacketLib.CSPingFormatter();
                case 5: return new MessagePack.Formatters.SBPacketLib.SCAuthFormatter();
                case 6: return new MessagePack.Formatters.SBPacketLib.SCChatMessageFormatter();
                case 7: return new MessagePack.Formatters.SBPacketLib.SCPongFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.SBPacketLib
{

    public sealed class ErrorCodeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.ErrorCode>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.ErrorCode value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((global::System.Byte)value);
        }

        public global::SBPacketLib.ErrorCode Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::SBPacketLib.ErrorCode)reader.ReadByte();
        }
    }

    public sealed class ResultCodeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.ResultCode>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.ResultCode value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((global::System.Byte)value);
        }

        public global::SBPacketLib.ResultCode Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::SBPacketLib.ResultCode)reader.ReadByte();
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.SBPacketLib
{
    public sealed class CSAuthFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.CSAuth>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.CSAuth value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(2);
            writer.Write(value.ServerTag);
            writer.Write(value.UserUID);
        }

        public global::SBPacketLib.CSAuth Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.CSAuth();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ServerTag = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.UserUID = reader.ReadInt64();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class CSChatMessageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.CSChatMessage>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.CSChatMessage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(13);
            writer.Write(value.ChatType);
            writer.Write(value.ServerTag);
            writer.Write(value.SendUserUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendUserName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendIcon, options);
            writer.Write(value.SendPortraitType);
            writer.Write(value.SendPortraitValue);
            writer.Write(value.SendUserGuildUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendUserGuildName, options);
            writer.Write(value.SendUserLastEnterTimeStamp);
            writer.Write(value.RecvUserUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Message, options);
            writer.Write(value.CurrTimeStamp);
        }

        public global::SBPacketLib.CSChatMessage Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.CSChatMessage();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ChatType = reader.ReadByte();
                        break;
                    case 1:
                        ____result.ServerTag = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.SendUserUID = reader.ReadInt64();
                        break;
                    case 3:
                        ____result.SendUserName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.SendIcon = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.SendPortraitType = reader.ReadInt64();
                        break;
                    case 6:
                        ____result.SendPortraitValue = reader.ReadInt64();
                        break;
                    case 7:
                        ____result.SendUserGuildUID = reader.ReadInt64();
                        break;
                    case 8:
                        ____result.SendUserGuildName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 9:
                        ____result.SendUserLastEnterTimeStamp = reader.ReadInt64();
                        break;
                    case 10:
                        ____result.RecvUserUID = reader.ReadInt64();
                        break;
                    case 11:
                        ____result.Message = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 12:
                        ____result.CurrTimeStamp = reader.ReadInt64();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class CSPingFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.CSPing>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.CSPing value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(3);
            writer.Write(value.ServerTag);
            writer.Write(value.UserUID);
            writer.Write(value.Timestamp);
        }

        public global::SBPacketLib.CSPing Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.CSPing();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ServerTag = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.UserUID = reader.ReadInt64();
                        break;
                    case 2:
                        ____result.Timestamp = reader.ReadInt64();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SCAuthFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.SCAuth>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.SCAuth value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SBPacketLib.ResultCode>(formatterResolver).Serialize(ref writer, value.Result, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SBPacketLib.ErrorCode>(formatterResolver).Serialize(ref writer, value.ErrorCode, options);
        }

        public global::SBPacketLib.SCAuth Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.SCAuth();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Result = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SBPacketLib.ResultCode>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.ErrorCode = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::SBPacketLib.ErrorCode>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SCChatMessageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.SCChatMessage>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.SCChatMessage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(13);
            writer.Write(value.ChatType);
            writer.Write(value.ServerTag);
            writer.Write(value.SendUserUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendUserName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendIcon, options);
            writer.Write(value.SendPortraitType);
            writer.Write(value.SendPortraitValue);
            writer.Write(value.SendUserGuildUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SendUserGuildName, options);
            writer.Write(value.SendUserLastEnterTimeStamp);
            writer.Write(value.RecvUserUID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Message, options);
            writer.Write(value.CurrTimeStamp);
        }

        public global::SBPacketLib.SCChatMessage Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.SCChatMessage();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ChatType = reader.ReadByte();
                        break;
                    case 1:
                        ____result.ServerTag = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.SendUserUID = reader.ReadInt64();
                        break;
                    case 3:
                        ____result.SendUserName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.SendIcon = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.SendPortraitType = reader.ReadInt64();
                        break;
                    case 6:
                        ____result.SendPortraitValue = reader.ReadInt64();
                        break;
                    case 7:
                        ____result.SendUserGuildUID = reader.ReadInt64();
                        break;
                    case 8:
                        ____result.SendUserGuildName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 9:
                        ____result.SendUserLastEnterTimeStamp = reader.ReadInt64();
                        break;
                    case 10:
                        ____result.RecvUserUID = reader.ReadInt64();
                        break;
                    case 11:
                        ____result.Message = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 12:
                        ____result.CurrTimeStamp = reader.ReadInt64();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SCPongFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::SBPacketLib.SCPong>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::SBPacketLib.SCPong value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            writer.WriteArrayHeader(3);
            writer.Write(value.ServerTag);
            writer.Write(value.UserUID);
            writer.Write(value.Timestamp);
        }

        public global::SBPacketLib.SCPong Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::SBPacketLib.SCPong();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ServerTag = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.UserUID = reader.ReadInt64();
                        break;
                    case 2:
                        ____result.Timestamp = reader.ReadInt64();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

